trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
- group: codecov

stages:
- template: lint-stage.yml
- template: test-stage.yml
  parameters:
    codecov.token: '$(codecov.token)'
