trigger:
  branches:
    include:
    - refs/tags/*
pr: none

variables:
- group: codecov
- group: twine

resources:
  repositories:
  - repository: templates
    type: github
    name: aio-libs/azure-pipelines
    endpoint: aio-libs

stages:
- template: lint-stage.yml
- template: test-stage.yml
  parameters:
    codecov.token: '$(codecov.token)'

- stage: dist
  jobs:
  - job: upload
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
        displayName: "Use Python 3.7"

      - script: |
          pip install -U setuptools twine wheel
        displayName: "Install tools"

      - script: |
          python setup.py sdist bdist_wheel
        displayName: "Make dists"

      - template: templates/step-store-dist.yml@templates

- template: templates/stage-publish.yml@templates
