trigger:
  branches:
    include:
    - refs/tags/*
pr: none

variables:
- group: codecov

stages:
- stage: test
  displayName: "Run tests"
  jobs:
  - template: tests-template.yml
    parameters:
      codecov.token: '$(codecov.token)'

- stage: deploy
  displayName: "Upload on PyPI"
  jobs:
  - job: upload
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
        displayName: "Use Python 3.7"

      - script: |
          pip install setuptools twine wheel
        displayName: "Instll tools"

      - script: |
          python setup.py sdist bdist_wheel
        displayName: "Make dists"

      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate"
        inputs:
          pythonUploadServiceConnection: pypi

      - script: |
          python -m twine upload -r "pypi" --config-file $(PYPIRC_PATH) --disable-progress-bar dist/*.whl
        displayName: "Upload to PyPI"
